import { MongoClient } from 'mongodb'
import pg from 'pg'

import { config } from './config.js'
import { pool } from './db.js'

/**
 * Tenant isolation model
 *
 * Postgres: every project gets its own database and its own login role on the shared
 * cluster. The role owns only its database, has no superuser/createdb/createrole
 * rights, and PUBLIC's default CONNECT grant is revoked so tenants can't reach each
 * other's databases (or the control-plane database).
 *
 * MongoDB: every project gets its own database and a user defined in that database
 * with `dbOwner` on it only. Users can't list or read other databases.
 */

export type Engine = 'postgres' | 'mongodb'

export type TenantCredentials = {
  databaseName: string
  username: string
  password: string
}

const IDENTIFIER = /^nb_[a-z0-9]+$/
const PASSWORD = /^[a-z0-9]+$/

function assertSafe({ databaseName, username, password }: TenantCredentials) {
  // Values are generated by us, but DDL can't use bind parameters, so verify anyway.
  if (!IDENTIFIER.test(databaseName) || !IDENTIFIER.test(username) || !PASSWORD.test(password)) {
    throw new Error('Refusing to provision with unsafe identifiers')
  }
}

const ident = (value: string) => pg.escapeIdentifier(value)

/** Locks the shared cluster down so new tenant roles can only reach their own database. */
export async function hardenPostgresCluster() {
  const { rows } = await pool.query<{ datname: string }>(
    `select datname from pg_database where datallowconn and datname not like 'nb\\_%'`
  )
  for (const { datname } of rows) {
    await pool.query(`revoke connect on database ${ident(datname)} from public`)
  }
}

export async function provisionPostgres(creds: TenantCredentials) {
  assertSafe(creds)
  const { databaseName, username, password } = creds
  await pool.query(
    `create role ${ident(username)} with login nosuperuser nocreatedb nocreaterole noreplication connection limit 30 password ${pg.escapeLiteral(password)}`
  )
  await pool.query(`create database ${ident(databaseName)} owner ${ident(username)}`)
  await pool.query(`revoke all on database ${ident(databaseName)} from public`)
  await pool.query(
    `grant connect, temporary on database ${ident(databaseName)} to ${ident(username)}`
  )
}

export async function deprovisionPostgres({
  databaseName,
  username,
}: Omit<TenantCredentials, 'password'>) {
  if (!IDENTIFIER.test(databaseName) || !IDENTIFIER.test(username))
    throw new Error('Unsafe identifiers')
  await pool.query(
    `select pg_terminate_backend(pid) from pg_stat_activity where datname = $1 and pid <> pg_backend_pid()`,
    [databaseName]
  )
  await pool.query(`drop database if exists ${ident(databaseName)}`)
  await pool.query(`drop role if exists ${ident(username)}`)
}

export async function rotatePostgresPassword(username: string, password: string) {
  if (!IDENTIFIER.test(username) || !PASSWORD.test(password)) throw new Error('Unsafe identifiers')
  await pool.query(`alter role ${ident(username)} with password ${pg.escapeLiteral(password)}`)
}

let mongoClient: Promise<MongoClient> | undefined

export function isMongoAvailable() {
  return config.mongoAdminUrl.length > 0
}

function getMongo() {
  if (!isMongoAvailable()) throw new Error('MongoDB is not enabled on this NicerBase instance')
  mongoClient ??= new MongoClient(config.mongoAdminUrl, { appName: 'nicerbase-cloud' })
    .connect()
    .catch((error) => {
      mongoClient = undefined
      throw error
    })
  return mongoClient
}

export async function provisionMongo(creds: TenantCredentials) {
  assertSafe(creds)
  const db = (await getMongo()).db(creds.databaseName)
  await db.command({
    createUser: creds.username,
    pwd: creds.password,
    roles: [{ role: 'dbOwner', db: creds.databaseName }],
  })
  // Materialize the database so it shows up immediately for the tenant.
  await db.createCollection('_nicerbase')
}

export async function deprovisionMongo({
  databaseName,
  username,
}: Omit<TenantCredentials, 'password'>) {
  if (!IDENTIFIER.test(databaseName) || !IDENTIFIER.test(username))
    throw new Error('Unsafe identifiers')
  const db = (await getMongo()).db(databaseName)
  await db.command({ dropUser: username }).catch(() => undefined)
  await db.dropDatabase()
}

export async function rotateMongoPassword(
  databaseName: string,
  username: string,
  password: string
) {
  if (!IDENTIFIER.test(databaseName) || !IDENTIFIER.test(username) || !PASSWORD.test(password)) {
    throw new Error('Unsafe identifiers')
  }
  await (await getMongo()).db(databaseName).command({ updateUser: username, pwd: password })
}

/** File name customers save the database CA certificate as (see /nicerbase-ca.crt). */
export const CA_FILE_NAME = 'nicerbase-ca.crt'

/** Whether customers must download our CA certificate to verify TLS connections. */
export const needsCaDownload = () => config.dbTls && !config.dbTlsVerified

export function connectionString(engine: Engine, creds: TenantCredentials) {
  const { databaseName, username, password } = creds
  if (engine === 'postgres') {
    // verify-full checks both encryption and the server's identity.
    let tls = ''
    if (config.dbTls) {
      // With a public CA, drivers use the system trust store (psql 16+: add sslrootcert=system).
      tls = needsCaDownload()
        ? `?sslmode=verify-full&sslrootcert=${CA_FILE_NAME}`
        : '?sslmode=verify-full'
    }
    return `postgresql://${username}:${password}@${config.postgresPublicHost}:${config.postgresPublicPort}/${databaseName}${tls}`
  }
  let tls = ''
  if (config.dbTls) tls = needsCaDownload() ? `&tls=true&tlsCAFile=${CA_FILE_NAME}` : '&tls=true'
  return `mongodb://${username}:${password}@${config.mongoPublicHost}:${config.mongoPublicPort}/${databaseName}?authSource=${databaseName}${tls}`
}
